### PR TITLE
empty contact photo

### LINKED ISSUE #121: ValueError: Path cannot be empty in /var/www/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php:93
**Describe the bug**
Crashing when running command classify-images

**To Reproduce**
Run command in shell.
Likely have a profile that has a bad photo in their profile.

**Expected behavior**
Not crash

**Recognize (please complete the following information):**
 - JS-only mode:no 
 - Enabled modes: object detection, face recognition

**Server (please complete the following information):**
 - Nextcloud: 22.2.3
 - RAM: 8GB
 - Processor Architecture x86

**Additional context**

My suspesion from checking out the code ( I dont realy know php), is that i dont see null or badformat handling when getting the format from the contacts.
Perhaps it should check that its not null, and some very basic format check? ( Its a base64 image i belive)

sudo -u www-data php /var/www/nextcloud/occ recognize:classify-images
Classifying photos of user eks
An unhandled exception has been thrown:
```
ValueError: Path cannot be empty in /var/www/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php:93
Stack trace:
#0 /var/www/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php(93): file_get_contents()
#1 /var/www/nextcloud/apps/recognize/lib/Command/ClassifyImages.php(92): OCA\Recognize\Service\ReferenceFacesFinderService->findReferenceFacesForUser()
#2 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Recognize\Command\ClassifyImages->execute()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /var/www/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#7 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#8 /var/www/nextcloud/occ(11): require_once('...')

```

Following changes seems to have stopped the issue, but should likely be made better.
bilde

### PR DESCRIPTION
**Pull request by bonswouar**
fix #121

### CODE REVIEW

**Comment by bonswouar** [comment]
@marcelklehr I've just added another commit to check earlier in the process if faces-recognition is enabled, to prevent useless parsing (and errors) of contact images

File: lib/Service/ReferenceFacesFinderService.php [hunk 1]
```diff
@@ -69,6 +74,9 @@ public function __construct(LoggerInterface $logger, IManager $contacts, IUserSe
      * @return array
      */
     public function findReferenceFacesForUser(string $userId):array {
+        if ($this->config->getAppValue('recognize', 'faces.enabled', 'false') !== 'true') {
+            return 0;
```
Comment (marcelklehr) [inline lib/Service/ReferenceFacesFinderService.php:78]: This violates the type hints. We should rather use `[]` here.

File: lib/Service/ReferenceFacesFinderService.php [hunk 2]
```diff
@@ -82,7 +90,7 @@ public function findReferenceFacesForUser(string $userId):array {
             }
             $cards = $book->search('', ['FN'], []);
             foreach ($cards as $card) {
-                if (!isset($card['PHOTO'])) {
+                if (empty($card['PHOTO'])) {
```
Comment (marcelklehr) [inline lib/Service/ReferenceFacesFinderService.php:93]: :+1:

File: lib/Service/ReferenceFacesFinderService.php (hunk 1 above)
Comment (marcelklehr) [reply lib/Service/ReferenceFacesFinderService.php:78]: Generally, I feel like the check does not belong in this class.

File: lib/Command/ClassifyImages.php [hunk 3]
```diff
@@ -90,9 +90,6 @@ protected function execute(InputInterface $input, OutputInterface $output): int
                 $this->imagenet->classify($images);
 
                 $faces = $this->referenceFacesFinder->findReferenceFacesForUser($user);
-                if (count($faces) === 0) {
```
Comment (marcelklehr) [inline lib/Command/ClassifyImages.php:93]: I'm happy with putting these checks into the respective `classify` methods (above as well).

Instead of putting the enabled checks into the finder logic, I'd say, let's put them explicitly into the command and background job classes. What do you think?

File: lib/Service/ReferenceFacesFinderService.php (hunk 1 above)
Comment (bonswouar) [reply lib/Service/ReferenceFacesFinderService.php:78]: @marcelklehr I didn't like this much either, but not sure where else this should be done as this is called from the Service and the Command and I didn't want to duplicate some code

File: lib/Command/ClassifyImages.php (hunk 3 above)
Comment (bonswouar) [reply lib/Command/ClassifyImages.php:93]: Yeah I didn't want to duplicate some code but that would certainly make more sense to have this check in the Service and the Command

Comment (marcelklehr) [reply lib/Command/ClassifyImages.php:93]: Let's duplicate the check for now. Eventually, we'll have to factor out the commonalities of the command and the background job into a common class anyway.
